### ISSUE TITLE
Only publish new version of each OSS Gadget tool if it has changed

### ISSUE THREAD

**Issue by gfs** [microsoft/OSSGadget#97] opened 2020-05-31 18:19 UTC
After #96 we have MultiExtractor building independently from all of OSS Gadget.  But each component of OSS Gadget really operates independently, and to reduce no-op version churn we should only publish new versions where there were changes.

**Comment by daalcant** [comment] 2020-06-29 17:44
This would require:
1. Separate pipelines for each component
2. Separate GitHub releases for each component
3. Separate release archives for each component
4. Separate instances of common resources, such as oss-downloader.exe, for each component, which increases total file size

We're currently releasing OSS Gadget as a single package by design, so I don't think this change is the way to go. Closing this issue for now, but we can discuss our release methodology if we decide we want to move this direction in the future.

**Closed by daalcant** 2020-06-29 17:44 UTC
Labels: enhancement, invalid, pipeline
